version: '3.9'
services:
  fastapi:
    build:
      context: ./fastapi
      dockerfile: Dockerfile
    container_name: fastapi
    ports:
      - '8001:8000'
    volumes:
      - ./fastapi:/usr/src/app
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - MODEL_CONFIG=${MODEL_CONFIG}
    depends_on:
      - laravel
    networks:
      - network1

  laravel:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: laravel
    ports:
      - '8000:8080'
    volumes:
      - .:/var/www
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - network1

  node:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run dev
    ports:
      - "3000:3000"
    volumes:
      - .:/var/www

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - network1

  phpmyadmin:
    image: phpmyadmin
    ports:
      - "8002:80"
    environment:
      PMA_HOST: mysql_db
    networks:
      - network1

volumes:
  db_data:

networks:
  network1:
    driver: bridge